graph LR
  AdminModule-->JwtModule
  AppModule-->AdminModule
  AppModule-->AuthModule
  AppModule-->EventsManagementModule
  AppModule-->JwtModule
  AppModule-->UploadModule
  AppModule-->UsersManagmentModule
  AuthModule-->JwtModule
  EventsManagementModule-->JwtModule
  MulterModule-->JwtModule
  UploadModule-->JwtModule
  UploadModule-->MulterModule
  UsersManagmentModule-->JwtModule